### ISSUE TITLE
Dashboard onderverdeling

### ISSUE THREAD

**Issue by fsuarezg** [CalZoneVUB/CalZone#103]
@gaethofs boven aan de dashboard pagina klopt de onderverdeling niet, er mist nog FR7 en de NFR1

**Comment by gaethofs** [comment]
Ik zal dit bijwerken, evenals alle requirements eens overlopen om de laatste versie online te hebben staan.

**Comment by Timbo925** [comment]
@fsuarezg heeft alle requirements zelf geupdate normaal gezien. Maar die lijst vanboven vonden we niet direct waar deze werd uitgehaald.

**Comment by Timbo925** [comment]
Ik veronderstel dat dit gedaan is. Moest het niet zo zijn laat dan iets weten
