### ISSUE TITLE
Logging folder location

### ISSUE THREAD

**Issue by endymion64** [CalZoneVUB/CalZone#108]
De logs worden in 2 folders opgeslagen: log en debugLog, maar de locatie van deze folders is nog niet correct. De config 'log4j.xml' maakt namelijk momenteel gebruik van een relatief pad, maar hierdoor komen deze (op mijn OS) op onverklaarbare reden in mijn eclipse folder... 
De locatie van de folders zou moeten gewijzigd worden naar een logischere plaats, maar voorlopig weet ik niet hoe ik dit dynamisch kan maken zodat dit voor ieder lokaal systeem dezelfde is.

**Comment by MPieter** [comment]
Aan welke logischere plaats had ge gedacht ?

**Comment by endymion64** [comment]
Ik had gedacht aan de folder 'calzone' (waar het deployscript zich bevindt)

**Comment by gaethofs** [comment]
Makes sense. Uiteindelijk behoort dat niet echt tot de code.

Op 22-mrt.-2014, om 14:00 heeft yocoppen notifications@github.com het volgende geschreven:
