### ISSUE TITLE
Tabbelen edditen 

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#109]
Ik ben bezig met wat na te denken over interface design. Momenteel zitten we met veel verschillende tabellen die we gaan moeten weergeven naar de user toe en tegelijkertijd sommige users laten toestaan deze aan te passen. Ik ben dan ook **X-editable** tegen gekomen om tabellen te edditen. Je kan hier een voorbeeld zien van hoe het werkt.

http://jsfiddle.net/xBB5x/3833/

Het maakt gebruikt van popups (of gaat ook inline) voor bepaalde velden aan te passen. Tis maar een optie en wou het dus eens delen. Deme staat op http://vitalets.github.io/x-editable/demo.html

**Comment by gaethofs** [comment]
Werkt inderdaad heel proper maar zou aparte AJAX queries moeten toestaan per veld dat wordt aangepast en dus een post request per parameter. Vanuit een goed ontwikkeld API-standpunt is dit wel geweldig :p.

Maar is er een meerwaarde om elk element apart te kunnen bewerken ipv een volledige rij in een tabel? Wel leuk voorstel.
