### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by gaethofs** [CalZoneVUB/CalZone#125]
```
server encountered an internal error. 
msg: The absolute uri: http://www.springframework.org/security/tags cannot be resolved in either web.xml or the jar files deployed with this application
```

Heb reeds geprobeerd de maven dependencies bij te werken, te refreshen, te herstarten, ... en dit een aantal keer, maar het probleem raakt niet volledig opgelost.

Na die stappen: HTTP Status 404 - /calzone

**Comment by Timbo925** [comment]
Dit is zoizo een jar file dat gedownload moet worden. Het is de taglib die in de jsp files alles oplost ivm bepaalde dingen te tonen aan het type ingelogde user. Zou moeten lukken door maven update te doen. Als dat niet lukt post ik wel snel even de nodig jar

**Comment by gaethofs** [comment]
Zou zeer welkom zijn aangezien ik nog geen oplossing heb gevonden en alleen maar tijd kwijt ben. Thanks in advance!

**Comment by Timbo925** [comment]
Denk dat het dees is https://www.dropbox.com/s/i8t9gytepwt6nvs/spring-security-taglibs-3.2.2.RELEASE.jar

**Comment by gaethofs** [comment]
Zit al bij de Maven Dependencies en raar maar waar, na een paar updates en herstarten, is de 404 error verdwenen en zit ik terug met de internal error van ervoor. Jeuj..

**Comment by Timbo925** [comment]
pom.xml en web.xml een openen en daar refreshen ?? Kijk er straks wel nog eens naar.

**Comment by gaethofs** [comment]
For future reference bij problemen:
- Clean project
- Update Project Dependencies
- Refresh
- Restart
  en als dat niet werkt:
- Server verwijderen en opnieuw inladen.
