### ISSUE TITLE
Inlezen Datadump

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#133]
@nicocarraggi Wanneer denk jij dat de datadump terug kan worden ingelezen in de database ? 

Ik en @yocoppen hebben deze namelijk nodig, vermits we onze scheduler op deze data willen laten werken. Telkens dummy data aanmaken duurt te lang.

**Comment by nicocarraggi** [comment]
Goed nieuws !! Het inlezen van lokalen is eindelijk gelukt. Ben nu wel niet thuis en heb geen deftige internet verbinding dus zal ik het pas tegen 20u kunnen afwerken en op git zetten.
