### ISSUE TITLE
Extra veld voor Assistenten/Professors

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#165]
@nicocarraggi @svdvonde 

De assistenten/professors krijgen de mogelijkheid om hun beschikbaarheid aan te duiden. Dit moet opgeslagen worden in de database.

**Comment by MPieter** [comment]
@nicocarraggi 

De klassen TeacherUnavailibity.java en TeacherLecturePreference.java zijn toegevoegd aan de repository. 

Kan jij ervoor zorgen dat deze opgeslagen kunnen worden in de database, de nodige services zijn aangemaakt, en ook de bijhorende sets in de User.java, ...

Voor TeacherUnavailibity.java:
- 1 professor kan meerder unavailibity's hebben.
- 1 unavailibility behoort tot 1 teacher.

Voor TeacherLecturePreference.java:
- 1 teacher heeft meerdere TeacherLecturePreferences
- 1 coursecomponent heeft ook meerdere TeacherLecturePreference
- 1 lecture preference heeft 1 teacher EN 1 CourseComponent

**Comment by svdvonde** [comment]
Ik ben al een tijdje aan het nadenken over hoe alles moet worden bijgehouden, want een hele tijd geleden hebben we die extra attributen tussen "course" en "user" ergens anders geplaatst, als ik me niet vergis... Dus in die relatie worden geen extra attributen bijgehouden, maar nu moeten er wel attributen voor specifiek "teachers" worden bijgehouden. Het is fout om deze bij "user" te plaatsen, want een user is niet noodzakelijk een teacher, maar dat is wel het simpelste (dan zouden die velden null zijn wanneer ze niet nodig zijn). De andere optie is een teacher subklasse van user, maar ik weet niet in welke mate er dan een refactoring moet gebeuren.

**Comment by Timbo925** [comment]
Het is inderdaad niet perfect om het bij user te zetten. Maar ik zou dit toch doen omdat het momenteel de makkelijkste en snelste optie is. Op deze manier gaan we er gewoon van uit dat alle users in ons systeem volledig gelijk zijn. Het enige wat hun dan onderscheid is hun 'role' wat dan een invloed heeft op de access die ze krijgen tot verschillende functionaliteit. 

Dit maakt het makkelijker. Want momenteel is het dan enkel nodig om dit role veld aan te passen als je users wilt promoveren. Anders zouden nieuwe users van een ander type moeten worden aangemaakt voor een nieuwe professor.

Momenteel dus zeker gaan voor de snelste optie als dit kan. Het 'beter' oplossen is niet echt de extra tijd waard imo.

**Comment by svdvonde** [comment]
Ik denk dat ik alles correct heb gedaan (maar het is ook al een tijdje geleden...). Test het wanneer je er klaar voor bent, en sluit deze issue wanneer het klaar is (of sluit nu en maak nieuwe issue)

**Comment by Timbo925** [comment]
Ok ziet er goed uit op het eerste gezicht. BTW handig dat ge commits maakt speciaal per issue da zouden we meer moeten doen :P
