### ISSUE TITLE
Foute Time Tracking

### ISSUE THREAD

**Issue by nicocarraggi** [CalZoneVUB/CalZone#17]
@gaethofs 

Heb vandaag gebruikt, terwijl het gisteren ( 9 dec ) moet zijn.

Nicolas User Management Back End    10/12/2013 17:30    10/12/2013 19:00    1h 30m  Details

**Comment by MPieter** [comment]
Issue staat op de verkeerde repository. Moet eigenlijk bij websitetheme-repo staan.

**Comment by gaethofs** [comment]
Fixed.
