### ISSUE TITLE
Room-model: Getters/Setters

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#171]
@nicocarraggi @svdvonde 

Enkele van de getters/setters volgen niet de java conventies.

Daardoor krijgen we problemen met onze scheduler.

Maken die namen van die getters/setters uit voor hibernate ?

**Comment by svdvonde** [comment]
Getters/Setters zijn niet relevant voor hibernate, maar soms vormen de automatisch gegenereerde getters/setters verschrikkelijke namen.. Maar bon, vertel maar welke anders moeten (of pas ze zelf aan met de Refactor > Rename functie van eclipse)

**Comment by MPieter** [comment]
Oke, prima ! Dan neem ik de getters/setters automatisch gegenereerd door eclipse volgens de java conventies.
