### ISSUE TITLE
Kan niet op 'Courses' in de Admin Dashboard

### ISSUE THREAD

**Issue by fsuarezg** [CalZoneVUB/CalZone#177]
pagina blijft maar eindeloos laden zonder dat de vakken uitgelezen worden, heeft dit te maken met database?

**Comment by Timbo925** [comment]
Zoizo want deze pagina heeft eerder al gewerkt. Dit zal gefixed worden denk ik door nico of sam

**Comment by svdvonde** [comment]
Dat is omdat nicolas veel return types veranderd heeft naar een Set ipv een List...

**Comment by Timbo925** [comment]
Hij heeft mij da gezegd dat da nodig was. Ik heb juist alle aanpassingen gedaan en de paginas moeten weer laden zoals gewoonlijk. Gewoon pullen
