### ISSUE TITLE
Course Data

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#183]
Op dit moment als ik findCourseByIdInitialized() doe is er nog steeds een null pointer naar courseData. 

Dit komt waarschijnlijk omdat we bij het inladen van de datadump geen lege course data aanmaken. Dit moet dus wel gebeuren zodat courseData altijd bestaat. Het kan geen kwaad dat er dan geen informatie is ingevuld op deze data

**Comment by MPieter** [comment]
Ondertussen heeft @nicocarraggi dit gefixt.

**Comment by MPieter** [comment]
Toch niet: @nicocarraggi fix dit.

**Comment by nicocarraggi** [comment]
Opgelost!
