### ISSUE TITLE
Master

### ISSUE THREAD

**Issue by nicocarraggi** [CalZoneVUB/CalZone#184]
Gelieve als je packages aanpast, dat deftig te doen en ervoor te zorgen dat de code blijft runnen als je die op de master zet ... Ik wou nu een uur werken in de auto, zal niet gaan ...

**Comment by Timbo925** [comment]
Het werkt bij mij. Dus mss update project , refresh en server eens verwijderen

**Comment by MPieter** [comment]
'.classpath' was de oorzaak.
