### ISSUE TITLE
Tomcat Status 500 Errors

### ISSUE THREAD

**Issue by gaethofs** [CalZoneVUB/CalZone#191]
Iemand één van deze problemen al tegen gekomen en kunnen verhelpen?

Bij het surfen naar een pagina:
![schermafbeelding 2014-04-18 om 01 06 34](https://cloud.githubusercontent.com/assets/2029424/2738040/c887f81c-c685-11e3-83d7-fecf2981be0c.png)

Bij het registreren:
![schermafbeelding 2014-04-18 om 01 07 26](https://cloud.githubusercontent.com/assets/2029424/2738037/b85e5166-c685-11e3-880b-a3f7227aa0e0.png)

**Comment by MPieter** [comment]
Nee, sorry. Bij mij werkt het alleszins, dus het zal aan u installatie liggen.

**Comment by MPieter** [comment]
@gaethofs Probleem al opgelost ondertussen ?

**Comment by gaethofs** [comment]
Jouw kopie van Eclipse heeft het opgelost. Blijft vreemd.
