### ISSUE TITLE
ReadCSVController.java

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#193]
@nicocarraggi 

Heeft de klasse ReadCSVController.java nog zin ? Anders kunnen we deze verwijderen.
Want op 1 of andere manier staan daar geen geldige ASCII characters in, volgens mijn javadoc compiler.

Alles wat in die klasse staat is toch uit gecommentarieerd.

**Comment by Timbo925** [comment]
Denk dat deze moet blijven bestaan want deze word gebruikt voor het uitlezen van de csv bestanden. Alles staat uit gecommentarieerd zodat niemand per ongeluk de controller kan aanspreken en zo database begint te reloaden.

**Comment by nicocarraggi** [comment]
Helemaal juist wat Tim zegt :)

**Comment by MPieter** [comment]
Oke, fix dan wel eens die rare tekens op lijn 85, 87 en 90. 

En z'n dingen moogt ge der wel liefst bijzetten in commentaar he. Een klasse die volledig in commentaar is staat is vrij vreemd en eigenlijk niet echt een manier van werken.
