### ISSUE TITLE
Hibernate: Setters voor variable die PK is.

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#194]
Kan ik voor bijv. de onderstaande variable een setter maken ? Is dit toegestaan door hibernate ? 

Dit vergemakkelijkt de testcode aanzienlijk omdat die equals methode wordt gebruikt voor objecten te vergelijken, die jullie overschreven hebben, en die enkel gebruik maakt van de ID-variable in een model.

Vermits ik ook in mijn unit tests niet langs de database passeer, moet ik een manier hebben om zelf een waarde te kunnen geven aan de id-variable.

public class CourseComponent {
    @Id
    @GeneratedValue
    @Column(name="CourseComponentID")
    private int id;

**Comment by Timbo925** [comment]
Ik denk wel dat dit mag. Enkel niet opslaan want hibernate gaat er waarschijnlijjk van uit dat je dit zelf niet kunt aanpassen en dan is de data niet perseen opgelagen eenmaal je diti doet.

**Comment by MPieter** [comment]
Oke, voorlopig heb ik er al setters bijgezet.

**Comment by svdvonde** [comment]
Setters voor primary keys mogen niet, tenzij je zelf een strategie toepast om primary keys te genereren - wat in ons geval niet zo is, want hibernate genereert die keys. Die equals methoden heb ik erbij gezet omdat ik dat gebruik in CourseServiceTest - om te zien of een object wel juist uit de database wordt gehaald. Wanneer je een andere equals methode nodig hebt moet je die zelf schrijven.

Twee objecten zijn gelijk als hun primary key gelijk is. Voor elke toepassing in de applicatie in een productieomgeving is dit een juiste uitspraak die het minst moeilijk is om te implementeren. Het alternatief is checken of alle velden gelijk zijn, maar dat is zoals je zelf al gemerkt hebt veel te veel werk. Het andere alternatief is checken of de geheugenlocatie van twee objecten gelijk is... Maar een kopie van een object is nog altijd hetzelfde object (in mijn visie van gelijkheid)

Hoe dan ook, een setter voor een primary key mag niet. Het is niet de bedoeling dat je methoden beschikbaar maakt die programmeurs eigenlijk niet mogen gebruiken. 

Geen idee wat er gaat gebeuren wanneer je een primary key van een object uit de database gaat veranderen en dat daarna terug opslaan.. Misschien kan dat perfect, maar hoe dan ook kan zoiets alleen maar leiden tot fouten.

**Comment by Timbo925** [comment]
Maak anders een aparte equalsName() methode ofzo. Ik veronderstel dat het enkel voor een vergelijking te doen is. Dus maakt ni echt uit welk veld je vergelijkt.

**Comment by MPieter** [comment]
- Ik kan geen aparte equalsName methode gebruiken, vermits drools die methode equals() automatisch aanroept.
- Dus ik mag dan wel alle hashCode + equals() methoden overschrijven ? Dit is wel veel meer werk dan enkel setters generen. Dan gaat jullie implementatie van hashCode + equals wel verloren.

**Comment by Timbo925** [comment]
Denk dat de beste optie toch de PK blijft. Zet ze mss deprectated met de informatie erbij dat dit niet mag gebruikt worden.  Enkel voor test data die niet mag worden opgeslagen. 

Want als je de gewone hash overschrijft moet het wel een volledig juiste zijn die alles checked en dit is wat te veel werkt.

**Comment by nicocarraggi** [comment]
Je kan de Equals herschrijven zodat ze niet alleen checken op Id maar op Id EN Name bvb :)

Je kan die heel eenvoudig laten genereren door Eclipse en aanvinken op welke attributen hij gaat vergelijken.

**Comment by MPieter** [comment]
Ik laat voorlopig de setters staan, dit is nu het gemakkelijkste en de snelste oplossing. Ik zal er in javadoc bijzetten dat dit enkel gebruikt mag worden voor testobjecten aan te maken.

Want @nicocarraggi & @svdvonde : het is idd handig dat eclipse dat automatisch kan genereren, maar dat lost niet op in mijn geval. Want als ik bijv. 4 standaard room-objecten aanmaak, hebben deze allemaal dezelfde veldjes. Waardoor die hashcodes nog steeds hetzelfde zullen zijn. Bijgevolg ziet drools die als hetzelfde object.

**Comment by svdvonde** [comment]
Gebruik dan geen lege objecten, waardoor het onderscheid wel te maken is.

**Comment by MPieter** [comment]
@yocoppen Is dit haalbaar ?

**Comment by endymion64** [comment]
De snelste fix is die setters voorzien.

Equals() aanpassen is gevaarlijk aangezien @svdvonde rekent op de semantiek van die functie...
EqualsName() ontwikkelen is theoretisch gezien mogelijk, maar dan moeten we weer al onze constraints herschrijven (en het was al moeilijk genoeg). Bovendien lijkt het mij moeilijker om unieke strings te voorzien dan unieke ints. Tenzij Java een int omzet in strings zoals je het verwacht: 123 --> "123" en geen random unicode-karakter

Ik ben graag lui dus ik vind deprecated setters voorzien voor die id's een acceptabele oplossing. We slaan toch niks op naar de db in die tests

**Comment by MPieter** [comment]
We hebben dus ervoor gekozen om de setters voor de ID's in de database objecten te behouden. Het staat er duidelijk in javadoc bij, dat dit enkel maar gebruikt mag worden voor test code.

Later als we een betere maar eenvoudige manier vinden kunnen we dit nog aanpassen.
