### ISSUE TITLE
Time Tracking

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#2]
Bij het toevoegen van een item komt er een lege rij bij in de tabel. Terwijl het formulier wel degelijk volledig is ingevuld.

Bij een andere poging kwamen er automatisch 2 rijen bij en gaf de browser een standaard foutmelding.

![image](https://f.cloud.github.com/assets/5703745/1459941/19196da2-4403-11e3-8c36-ef1425a170ed.png)

**Comment by gaethofs** [comment]
Is blijkbaar een fout opgetreden bij het invullen of oppikken van de gegevens uit het formulier bij het AJAX-request. Ik zal de JavaScipt en PHP-code voor het indienen een beetje robuuster maken, zodat de gegevens harder worden gecontroleerd en er duidelijkere foutmeldingen worden gegeven. Bijv. "datum werd fout verwerkt" i.p.v. "er is iets fout gelopen".

Kan je nog even meegeven welke browser je hebt gebruikt en hoe je de datum plugin te zien krijgt?

**Comment by MPieter** [comment]
Ik gebruik Chrome.Ondertussen heb ik wel al gemerkt dat er 2 van de 3 requests nu wel juist in terecht zijn gekomen.

Screenshot van het log-scherm: 
![image](https://f.cloud.github.com/assets/5703745/1459999/8f8b8886-4407-11e3-8176-e6fa9410d3dc.png)

**Comment by gaethofs** [comment]
Ik heb de fout gevonden denk ik. Bij de gebruikersinstellingen stond er standaard een ander datum formaat opgegeven dat hetgeen dat in het profiel wordt gebruikt. De data moet van de vorm 02/11/2013.. zijn, terwijl dit bij de gebruiker werd gelezen als 2 okt. 2013. Bij mij was dit al aangepast, daarmee dat ik er had over gekeken. Het is nu overal aangepast, dus normaal gezien zou het probleem hiermee moeten zijn opgelost.

**Comment by MPieter** [comment]
Ik heb het net nog eens geprobeerd, zelfde fout:

![image](https://f.cloud.github.com/assets/5703745/1460036/62c3830a-440a-11e3-9a99-2bdbb4b4bd01.png)

**Comment by gaethofs** [comment]
Geeft inderdaad nog altijd een fout. Ik zal eens dieper checken wat het probleem is, maar het ligt in elk geval al zeker bij het AJAX-request. Volgens mij wordt er een 500 error teruggegeven na het indienen van de gegevens. Ik dacht dat dit al was opgelost, want bij mij lukt het toevoegen wel. Kan je even kijken wat er gebeurd bij het request zelf?

In Chrome kan je dit als volgt via het menu:
- Weergave > Ontwikkelaar > JavaScript-console

Er zou dan duidelijk een error moeten staan bij het request.
Voorlopig heb ik het formulier op de website even gesloten, om zelf eerst eens te testen of alles wel goed werkt.
Als ik het niet vind, kan je best zo eens even kijken of het inderdaad een 500 error is.

**Comment by MPieter** [comment]
Ik heb het nu nog eens geprobeerd, ik krijg nog steeds een error: 
![image](https://f.cloud.github.com/assets/5703745/1460927/76e14856-4480-11e3-97e4-0b39615293fc.png)

Volgende melding komt op de console: Failed to load resource: the server responded with a status of 404 (Not Found) http://wilma.vub.ac.be/~se2_1314/website/themes/theme/assets/js/jquery-1.10.2.min.map

Dit is dan het resultaat op de pagina:

![image](https://f.cloud.github.com/assets/5703745/1460928/8ae19888-4480-11e3-91d8-f8d26ecd1821.png)

**Comment by gaethofs** [comment]
Ik ben er nog altijd niet helemaal uit, maar er is wel al wat verbeterd.
- bij het indienen van het formulier worden de velden geblokkeerd om het maken van meerdere requests te blokkeren,
- specifieke meldingen per fout, voor een duidelijker debuggen of blokkeren,
- PHP-code checkt nu ook alle data, hier moet ik nog een check toevoegen voor strengere controle van de datum string.

De error die je hier krijgt is hier niet zo belangrijk. Dat is omdat Chrome dit kan vragen bij de console (wanneer jQuery wordt gebruikt). Voor sourcemap-aware browser zoals Chrome zal ik dat bestand apart moeten toevoegen bij het JavaScript.

Kan je eens proberen of je vanuit een andere browser nog steeds hetzelfde probleem hebt?
Het request wordt wel goed uitgevoerd, maar de manier waarom de datums worden geparsed klopt niet helemaal blijkbaar.
Ik zal een aparte log aanmaken die de rauwe data van het formulier dumpt voor het time tracken.

**Comment by MPieter** [comment]
Dit is het resultaat geprobeerd met Internet Explorer. Het komt nu ook gewoon terug in de tabel zonder dat er iets ingevuld is.

![image](https://f.cloud.github.com/assets/5703745/1461055/82408190-448e-11e3-84e9-a32575c66d27.png)

**Comment by gaethofs** [comment]
Gebeurt op het eerste zicht niets fout en de titel en beschrijving zijn altijd wel weggeschreven dus dan is het echt wel het parsen van de datum in JavaScript. Anders moet ik dat pas in PHP laten gebeuren. Ik haal de pagina even offline totdat ik dat heb bijgewerkt. 

Alvast bedankt voor de feedback. Werkt productief zo.

**Comment by gaethofs** [comment]
Kan je via de browser nog eens een nieuw verzoek indien? Normaal zou je nu een melding moeten krijgen met de datavariabelen. Dit zou in de aard moeten zijn van:

From: Sun Nov 03 2013 16:56:00 GMT+0100 (CET)- To: Sun Nov 03 2013 16:56:00 GMT+0100 (CET)

**Comment by MPieter** [comment]
De functie is nog geblokkeerd voor debugging. Vergeten terug aan te zetten ?

**Comment by gaethofs** [comment]
Staat terug actief nu. Had er inderdaad over gezien omdat ik als webmaster was ingelogd en ik dat dan wel nog zie.
Bij het toevoegen zal er nu geen record worden aangemaakt. Er verschijnt enkel een melding met de datums.

**Comment by MPieter** [comment]
Het resultaat (in Chrome):

![image](https://f.cloud.github.com/assets/5703745/1461293/c69aa596-44a2-11e3-945a-7d998aa5169e.png)

**Comment by gaethofs** [comment]
Dan wordt hij wel juist geparsed maar fout doorgegeven blijkbaar. Ik heb het veranderd zodat er altijd een standaard UTC string wordt doorgegeven en deze dan in PHP wordt omgezet.

Ik heb in de code ook een log toegevoegd waar de rauwe data in terecht komt. Dit zal ik ook allemaal opnemen in het SCMP.

Als het nu niet zou lukken, dan laat ik het parsen weg uit JavaScript en laat ik alles op de server gebeuren, maar iets zegt mij dat het opgelost zou kunnen zijn nu. Kan je nog een proberen?

**Comment by MPieter** [comment]
Ja, nu is het inderdaad in orde!
