### ISSUE TITLE
Taggen van de eerste iteratie

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#20]
@gaethofs @Timbo925 

> Alle documenten en source code worden worden overeenkomstig getagd/gebranchd (seN-iterM) in de repository.

Vermits ik hier geen rechten voor heb, moeten jullie dit doen.

Liefst voor vandaag 9u!

**Comment by Timbo925** [comment]
Kheb nu ook nogmaals getagged ipv te branchen

**Comment by MPieter** [comment]
Kunt ge dat ook doen voor de documenten ?

**Comment by Timbo925** [comment]
Oeps inderdaad vergeten. Is nu in orde
