### ISSUE TITLE
Extra veld voor Course-model & Traject-model

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#201]
@nicocarraggi 

In het Course-model en Traject-model moet er een extra boolean 'frozen' bijkomen. 

Dit is net zoals bij het 'Entry' model.

De setters van deze boolean vereisen waarschijnlijk extra applicatielogic, maar die zal ik er wel inzitten.

**Comment by nicocarraggi** [comment]
Done!

**Comment by endymion64** [comment]
@nicocarraggi 
Er moeten meer databasemethoden komen voor Entry's  om het bevriezen werkbaar te maken:
- getAllEntriesFromCourseComponent(CourseComponent cc)
- geAlltEntriesFromCourse(Course c)
- getAllEntriesFromTraject(Traject t)
  Aangezien we op die niveaus entries willen kunnen bevriezen, willen we dus heel simpel aan de juiste sets geraken.
- updateEntries(Set<Entry> entrySet) (om een gehele reeks van aanpassingen te updaten)

**Comment by endymion64** [comment]
Wegens gebrek aan respons heb ik mijzelf beholpen zonder database transacties te maken...
