### ISSUE TITLE
Homepagina: Dynamisch waarden ophalen

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#204]
@Timbo925 @gaethofs 

Op de homepagina moeten de drie dropdown boxen dynamisch geleden worden met de gegevens uit de database mbv calls naar de API.

Alsook moeten de juiste entry's worden opgehaald uit de database voor weergave in de kalender.

**Comment by MPieter** [comment]
@svdvonde  @Timbo925 Gebeurd ?

**Comment by gaethofs** [comment]
Dit zou allemaal moeten werken.
De homepage is ook aangepast voor het bookmarken. Bij de keuze van een lessenrooster wordt er automatisch een hash aan de url toegevoegd. Refreshen of bookmarken zal dan de pagina met de juiste lessenrooster herladen/opslaan.

**Comment by svdvonde** [comment]
Dit is inderdaad gebeurt. De keuzes komen uit de database, en de selectie van de tweede waarde bepaald de keuzes van de tweede dropdown. Met deze waarden wordt nog niets gedaan (omdat je toen nog geen lessenrooster op een kalender kon plaatsen - geen idee hoe dat nu is)

**Comment by gaethofs** [comment]
Das is allemaal volledig afgewerkt en laad nu dus lessenroosters.
