### ISSUE TITLE
Notification opslaan in de database

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#207]
@nicocarraggi @Timbo925 

Het model com.vub.Notification moet opgestaan worden in de database.

@Timbo925 Kunt gij nog even verifiëren of hier alle benodigde velden aanwezig zijn in dit model ?

**Comment by MPieter** [comment]
Het lijkt mij ook handig zijn om het tijdstip waarop de notificatie gegenereerd is op te slaan, zodanig dat we dit ook kunnen tonen. Wat denken jullie hiervan ?

**Comment by Timbo925** [comment]
Ik zou er inderdaad wel nog 1 datum veld bijzetten. Noem het gewoon date.
Dit kunnen we dan gebruiken om notificaties te ordenen en zo weten we ook wanneer notificaties plaatsvinden en eventueel automatisch verwijderd mogen worden.

**Comment by nicocarraggi** [comment]
Done!
