### ISSUE TITLE
Notifications dynamisch ophalen

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#208]
@gaethofs @Timbo925 

In ApiNotifications.java moeten de Notifications dynamisch worden opgehaald uit de database. 

@nicocarraggi Laat iets weten wanneer dit Notification-object in de database is aangemaakt en de services klaar zijn. Zodanig dat dit geïmplementeerd kan worden.

**Comment by Timbo925** [comment]
Notificaties moeten gegenereerd worden als er aanpassingen worden gedaan aan entry's. Momenteel gaat dit nog niet direct omdat we deze pagina niet hebben. Als ik kan opslaan en verwijderen uit de database zou dit wel niet moeilijk moeten zijn.

**Comment by nicocarraggi** [comment]
Done!

**Comment by MPieter** [comment]
@gaethofs @Timbo925 

Jullie kunnen dit nu implementeren.

**Comment by Timbo925** [comment]
Worden opgehaald uit de database en elke pagina houd het aantal notificaties in het oog
