### ISSUE TITLE
CSS van login pagina en profiel pagina

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#21]
@gaethofs @Timbo925 

CSS van login pagina en profiel pagina ontbreekt nog.

Zou ge mij ook de reden kunnen zeggen waarom hiervoor geen CSS is opgeleverd? En waarom er hierover niet gecommuniceerd is ? Tim zei namelijk dat gij (christophe) onbereikbaar waart ?

Deadline: dinsdag 17/12/2013 zodanig dat we het op de presentatie nog kunnen tonen.

**Comment by Timbo925** [comment]
Ik had gewoon een mail verstuurd en was geen reactie op gekomen. @gaethofs laat zeker iets weten of het gaat lukken tegen dinsdag anders moet ik het nog verdelen aan iemand anders toewijzen om deze nog snel te maken. 

Niemand heeft denk ik direct ervaring met dit te doen dus zou wel handig zijn als je dit zelf nog rap zou kunnen doen. Merci

**Comment by Timbo925** [comment]
@gaethofs Gelezen? :)

**Comment by gaethofs** [comment]
Heb het gelezen. Ik had dit weekend geen computer ter mijne beschikking en ben tot net ook amper ter plaatse gebleven. Ik zal zien dat ik dit morgen snel kan maken.

**Comment by MPieter** [comment]
@Timbo925 Ik kan er op rekenen dat tegen vanavond dit in orde gebracht is ?

**Comment by Timbo925** [comment]
Als ik de paginas krijg van @gaethofs kan ik het online zetten. Hoe ver zit je daarmee @gaethofs ?

**Comment by gaethofs** [comment]
Ben er met bezig ;). Ik veronderstel dat de login/home pagina min of meer hetzelfde is als de huidige login pagina maar zonder formulier dan. Anders is een redirect naar de login nog beter eigenlijk. De profiel pagina is in de stijl van bootstrap maar dan met onze layout. Mag ik die veranderingen allemaal naar het CalZone project pushen of hebt ge liever dat ik u de CSS/HTML files bezorg? Anders steek ik ze ineens in CalZone.

**Comment by Timbo925** [comment]
Rechtstreeks op CalZone liefs. Ik zet het dan wel online

**Comment by MPieter** [comment]
Dit is ondertussen ook in orde. Prima !
