### ISSUE TITLE
DeploymentScript

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#210]
@yocoppen 

Wat heb jij nu moeten doen woensdagmorgen om calzone te deployen op de wilma server ? Dan kunnen we misschien eindelijk het deploy script voor goed en voor altijd fixen.

**Comment by Timbo925** [comment]
Ik denk da het zo moet gebeuren.
- Hernoem .war naar .uploadwar
- Upload
- Stop server
- Delete oude .war en /calzone
- Hernoem .uplaodwar
- Start server

**Comment by MPieter** [comment]
Oke, ik zal dit eens implementeren en kijken of het dan werkt.

Kan @yocoppen toch nog eens zeggen welke procedure hij gevolgd heeft woensdagmorgen ?

**Comment by endymion64** [comment]
Hoe ik het manueel doe:
- upload .war naar juiste locatie waardoor de oude .war overschreven wordt
- sluit server
- verwijder calzone folder
- start de server (hierdoor wordt nieuwe calzone folder uit de nieuwe .war gegenereerd)
- test connectie door naar de url te surfen

Ergens vermoed ik ook dat het script te snel draait om deze methode vlekkeloos te laten verlopen. Als een script een server sluit en start zit daar amper verschil in tijd op... Ik denk dat het dus aan te raden is om een hold/wait van 5 seconden in het script te stoppen ergens tussen het sluiten en herstarten van de server.

Het laatste bizarre dat mij opviel aan het script was dat hij compile en build errors gaf terwijl ik het manueel wel kon doen  zonder errors (met exact dezelfde commando's).

**Comment by MPieter** [comment]
Ik heb u procedure dus gevolgd, en dat werkt niet bij mij. Calzone op de wilma server is dan ook nu down. 

Der is dus iets aan mijn installatie dat er voor zorgt dat het niet werkt.

Ik stel voor dat gij bij u dat dan eens van die pauze gebruikt.  Hieronder is al een snippit waar er 5 seconden sleep is toegevoegd.

```
echo "Restarting tomcat at wilma..."
sshpass -p 'Bean59Cabal' ssh se2_1314@wilma.vub.ac.be "rm -r ~/apache-tomcat-7.0.52/webapps/calzone && cd apache-tomcat-7.0.52/bin && ./shutdown.sh && sleep 5 && ./startup.sh"
```

**Comment by endymion64** [comment]
Ik zal er mij komende coding sessie mee bezighouden dan als da goed is voor u?

**Comment by MPieter** [comment]
Dees is iets voor tussendoor. Ik heb liever dat ge vanavond werkt aan de performantie van de scheduler, das belangrijker.

EDIT: Dus doe dees dan wanneer ge eens tijd hebt. Is niet dringend. Voorlopig moet gij dan wel telkens manueel deployen via u pc. Vermits gij met uw pc geen problemen hebt.
