### ISSUE TITLE
EntryService: Toevoegingen

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#211]
@nicocarraggi Aan de entryService moeten volgende mogelijkheden worden toegevoegd:
- find entry's by course
- find entry's by traject
- find entry's by user (Let op hier: voor studenten is dit voor de vakken waarop ze zijn ingeschreven, voor assistenten/professoren is dit voor de vakken die ze geven)
- find entry's by room

**Comment by nicocarraggi** [comment]
Entries van een Course: get de entries van elke coursecomponent van de course.
Entries van een Traject: alle entries van elke course. ( vrij zwaar dus ? )
Entries van een User: alle entries van elke course. ( idem )
Entries van een Room: room.getEntries()

Entries is altijd een lazy set maar met Tim zijn oplossing zou je dit altijd kunnen opvragen.

**Comment by nicocarraggi** [comment]
Fix voor het simpeler te maken voor jullie:
Entries van een Course / Traject / User zal via de Service gaan met getAllEntries(...).
Voor Room is het simpelweg room.getEntries().
