### ISSUE TITLE
Initialized vakken

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#212]
Het moet mogelijk worden om vakken op te halen waarvoor de coursecomponents alsook de lesgevers van deze coursecomponents geinitializeerds zijn. Dit is nodig voor de enrolled courses pagina's.

**Comment by Timbo925** [comment]
@nicocarraggi  @svdvonde

**Comment by svdvonde** [comment]
Is het niet beter om gewoon één procedure te maken die de hele klasse initialiseert, zodat je niet n^2 methoden moet voorzien voor alle combinaties van "dit en dat initialiseren"?

**Comment by Timbo925** [comment]
Zou beter zijn. Momenteel is het enkel mogelijk om de classe zelf terug te halen . Probleem is dus dat voor de enrolledcourses pagina we 'dieper' moeten initialiseren. Weet dus niet hoe we dit doen.

**Comment by nicocarraggi** [comment]
Tim, ik had je dit toch uitgelegd? gewoon size() gebruiken in de service file. 

Dus als je teachers moet hebben van elke coursecomponent van een course dan doe je eerst
 course.getCourseComponents().size();
En dan 
for(CourseComponent cc : course.getCourseComponents()){
 cc.getTeachers.size();
}

Dus bij findCourseByName(String name) moet je die code van hierboven net de lijn vóór de return zetten.

**Comment by Timbo925** [comment]
Ok heb dit geimplementeerd

**Comment by Timbo925** [comment]
Toch nog een probleem. Dit is momenteel mijn querry voor gewoon een alle courses op te halen waarvan ik ook de teachers hun naam wil kennen.

``` java
@Transactional
    public Set<Course> getCoursesInitialized() {
        Set<Course> result = new HashSet<Course>();
        result.addAll(courseRepository.findAll());

        for (Course c : result) {
            for(CourseComponent cc : c.getCourseComponents()) {
                for (User u : cc.getTeachers()) {
                    u.getPerson();
                }
            }
        }
        return result;
    }
```

Deze code uitvoeren duurt 1+ minuut wat dus niet accepteerbaar is. Grootste probleem is denk ik dat hij alles lazy gaat ophalen maar dit natuurlijk 100x. Volgens mij is het op te lossen door custom query te schrijven te schrijven maar weet niet hoe dit gaat en is werk voor het database Team.

**Comment by Timbo925** [comment]
@nicocarraggi  @svdvonde

**Comment by nicocarraggi** [comment]
Je kan al die for lus over Teachers wegdoen en vervangen door:

cc.getTeachers.size()

Ik weet niet ivm de duur van het ophalen, maar volgens mij zal het zeker niet sneller gaan als je zelf een query schrijft ... ( dit zou de snelste manier moeten zijn ).

**Comment by Timbo925** [comment]
Die loop moet er wel nog bij want moet de naam van teacher hebben en dat zit in User.person

Dit is zoizo niet efficient he. Hij gaat telkens voor het object dat hij nog niet kent een nieuwe querry invoeren naar de database. Dit zou in 1 grote query moeten komen.

**Comment by nicocarraggi** [comment]
Neen normaal als je de size() van Teachers vraagt worden alle User objecten geladen EN het gelinkte Person object ook. ( want dat is een 1 op 1 relatie dus normaal gezien moet die EAGER zijn, als dat niet zo is moet dat gefixt worden :) )

**Comment by Timbo925** [comment]
Ok maar daar zit de vertraging zeker niet. Er zijn maar iets van een 20 teachers effectief in de database dus gelinkt aan vakken momenteel. 

Momenteel heb ik eens wat timingen gezet bij de CourseService. Het uitvoeren van getCourses() duurt momenteel 28 seconden voor 580 courses op te halen.  Dit lijkt me toch niet echt performant  :/

**Comment by nicocarraggi** [comment]
Ik ben daar nu geen pro in maar kan het ook niet trager zijn omdat de database "op een andere locatie" is en niet "lokaal" ?

**Comment by Timbo925** [comment]
Mogelijk zou het eens moeten testen

**Comment by svdvonde** [comment]
Het is ook niet de bedoeling dat je de database draait op een andere server. Wanneer de database lokaal draait zijn die queries bliksemsnel. Ping eens naar wilma, en vermenigvuldig dat met het aantal queries dat hij moet uitvoeren... 580 courses duurt 30 seconden, dat is +- 50ms per course. Dat ligt toevallig in dezelfde orde als pingen naar de vub en een antwoord krijgen. 

ik zou me dus niet te veel zorgen maken over database performantie als de database ergens anders draait.

**Comment by Timbo925** [comment]
Inderdaad heb juist een test uitgevoerd en het ophalen duurt lokaal 60 seconden en met op wilma te deployen is dit  1 seconden. Wel een grote verbetering dus :+1:

**Comment by nicocarraggi** [comment]
Ah nice ik had dus gelijk :p wat gaan we er dan aan doen?

**Comment by Timbo925** [comment]
Weinig aan te doen ik schrijf nu gewoon snel een query bij die er maar 20 ophaalt zodat het wat sneller gaat voor mijn testen.

**Comment by svdvonde** [comment]
1 seconde is nog altijd te lang. Wanneer je op wilma deployed moet je de url van de database op localhost zetten ipv de externa url wilma.vub.ac.be

**Comment by Timbo925** [comment]
Heb mijn database lokaal gezet om toch sneller te kunnen werken met de volledige data. Ik heb daarom ook percistence.xml moeten aanpassen naar dit.

``` xml

<bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
        <property name="driverClassName" value="com.mysql.jdbc.Driver" />
        <property name="url" value="jdbc:mysql://wilma.vub.ac.be/se2_1314_2" />
        <property name="username" value="se2_1314" />
        <property name="password" value="Bean59Cabal" />
    </bean>

    <bean id="dataSourceLocal"
        class="org.springframework.jdbc.datasource.DriverManagerDataSource">
        <property name="driverClassName" value="com.mysql.jdbc.Driver" />
        <property name="url" value="jdbc:mysql://127.0.0.1/se2_1314_2" />
        <property name="username" value="root" />
        <property name="password" value="warcraft" />
    </bean>

    <bean id="entityManagerFactory"
        class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean">
        <property name="dataSource" ref="dataSource" />
        <property name="persistenceUnitName" value="hsqldb-ds" />
        <property name="persistenceXmlLocation" value="classpath:META-INF/persistence.xml"/>
</bean>
```

Als je dan lokaale db wilt gebruiken moet je gewoon dit veranderen van 

``` xml
<property name="dataSource" ref="dataSource" />
naar
<property name="dataSource" ref="dataSourceLocal" />
```

In de folder /Readme MySql/Backup 28/4 staan de 2 databases die je moet inladen in je locale database om overeen te komen met de database op deze datum. Nadien als er veranderingen nodig zijn kunnen we makkelijk weer nieuwe bestanden aanmaken om de locale databes gelijk te krijgen met de nieuwe code.
