### ISSUE TITLE
JUnit Testing: Repitition

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#216]
@yocoppen @svdvonde 

Zoals het nu zit, worden de Unit testen van onze scheduler 10x herhaald om rekening te houden met de random-factor die in de scheduler-configuratie zit.

Ragnhild gaf hier volgende commentaar op:

Random testen gebruiken "echte" random: testen zijn daardoor niet deterministisch. Een pseudo-random generator kan helpen voor de testen.

Wat denken jullie hiervan ? Ik vermoed dat Jens ons verkeerd heeft geintrepeteerd door te denken dat onze Random-factor in de testen zelf zit ?

**Comment by endymion64** [comment]
Ik denk dat ze vermoeden dat wij die random factor in OptaPlanner kunnen manipuleren met een seed. Helaas hebben we die controle niet in OptaPlanner aangezien dit gewoon een node van de XML config-file van de Solver is:

``` xml
 <selectionOrder>RANDOM</selectionOrder>
```

De documentatie spreekt niet over een seed of pseudo-random generator die wij kunnen opstellen/meegeven in deze config. Men kan een andere selectie-orde kiezen, maar dit is niet schaalbaar en wij mikken op een schaalbare configuratie.

**Comment by svdvonde** [comment]
Sluit dit issue maar: "working as intended"
