### ISSUE TITLE
FR 1.3: Wachtwoord vergeten

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#22]
Als ik op 'click here' klik, gebeurt er niets.

Youri zegt dat deze requirement in progressie is, wat is er dan al van gerealiseerd ? 

Belangrijk voor als we dit morgen willen demonstreren.

![image](https://f.cloud.github.com/assets/5703745/1763320/ddda3caa-670a-11e3-9961-a86f67a0c12c.png)

**Comment by Timbo925** [comment]
Nog niks voor gedaan. Het zelfde systeem zal gebruikt worden als activatiemails dus alle onderdelen werken in princiepe al

**Comment by MPieter** [comment]
Oke, genoteerd.
