### ISSUE TITLE
Scheduler: AdvancedScheduling

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#236]
@yocoppen  @MPieter

De score in de test "advancedScheduling" zou eigenlijk 0/0 moeten bereiken. Momenteel lukt dit niet.

Ik zie 2 opties:
- de configuratie van de scheduler nog verder aanpassen zodanig dat andere meer radicale oplossingen sneller gevonden worden
- de uren slots verminderen: we kiezen ervoor om bijvoorbeeld enkel lessen te plannen om 9u, 11u, 13u en 15u. En dus niet de mogelijkheid geven om ook lessen op 8u, 10 etc te geven. Dit zal de scheduling vergemakkelijken.

@yocoppen Wat denk jij ? De tweede optie lijkt mij het gemakkelijkste, iets minder vrijheid maar wel wel al een pak eenvoudiger.

**Comment by endymion64** [comment]
Laten we vertrekken van optie 2.
Zodra dat werkt, kunnen we misschien terug overwegen om meer flexibilitiet in de slots te voorzien

**Comment by MPieter** [comment]
Optie 2 werkt redelijk goed nu. 

Laten we het bij de eenvoudigste oplossing houden.
