### ISSUE TITLE
Admin dashboard feedback

### ISSUE THREAD

**Issue by nicocarraggi** [CalZoneVUB/CalZone#244]
Bij het aanmaken van een nieuwe course zou het ideaal zijn moest er, bij het submitten van de nieuwe course, IETS gebeuren? een soort feedback want nu gebeurt er niets en lijkt het alsof submit niets doet... terwijl die wel degelijk opslaat.

**Comment by nicocarraggi** [comment]
Hetzelfde geldt bij het deleten van een Course.

**Comment by MPieter** [comment]
Bij het deleten van een course moeten we de feedback implementeren door die table row in kwestie te hidden en dan is een page refresh niet nodig.

@svdvonde Fix gij dit ? OF @fsuarezg

**Comment by nicocarraggi** [comment]
En ook eventueel een kleine popup die zegt dat het effectief verwijderd is.

Nog een vraag/opmerking over het dashboard:
Bij het aanpassen van een (bestaande) Course, is het niet mogelijk van course components toe te voegen / verwijderen?

**Comment by MPieter** [comment]
Ik betwijfel ofdat er eigenlijk functionaliteit voorzien is om course components toe te voegen / verwijderen. Ik dacht dat hier te weinig tijd voor was.

**Comment by MPieter** [comment]
@Timbo925 Ben ik juist ?

**Comment by Timbo925** [comment]
Dat is er inderdaad niet bij een course. Bij traject is het wel dus mss lukt het wel om dit nog te doen. Mss nog iets dat @svdvonde of @fsuarezg kan doen want ik ga nog werk genoeg hebben met de rest van de front-end

**Comment by svdvonde** [comment]
Geen idee hoe je dat met het toevoegen doet, maar dat deleten zal ik proberen te doen.

**Comment by MPieter** [comment]
@svdvonde Dit is toch niet opgelost ? 

Als ik een course probeer te deleten, gebeurt er nog steeds niet. Pas bij een page refresh is er een verandering te zien.

(En ik zit wel degelijk op de laatste master)

**Comment by svdvonde** [comment]
Werkt wel bij mij (Opera browser). Wat staat er in je javascript console?

**Comment by MPieter** [comment]
Dit is het enige dat ik kan vinden:

![screen shot 2014-05-15 at 12 49 12](https://cloud.githubusercontent.com/assets/5703745/2983135/a2637a9a-dc1e-11e3-98cb-bf2af17907fe.png)

**Comment by svdvonde** [comment]
Die error heeft niets te maken met de pagina van de courses (overigens heb ik die ook). Dus het zou gewoon moeten werken... Opera gebruikt de Blink engine, dus in Chrome zal het ook werken. Mischien moet iemand anders het eens in firefox/safari testen?

**Comment by MPieter** [comment]
Mijn browser is Safari. En dat is de JavaScript console.
