### ISSUE TITLE
Admin dashboard add course

### ISSUE THREAD

**Issue by nicocarraggi** [CalZoneVUB/CalZone#248]
Wanneer een nieuwe course component wordt toegevoegd krijg je bij "start date" als text : Week of academic year, terwijl bij "end date" er als text gewoon : course component staat. Kan iemand dat veranderen zodat er bij "end date" ook : Week of academic year staat?

**Comment by nicocarraggi** [comment]
Bij "contact hours", "class duration", "capacity", "room requirement" en "semester" staat er ook gewoon : course component.

**Comment by nicocarraggi** [comment]
[CourseComponent [id=0, type=HOC, term=S2, contactHours=26, startingDate=2, roomCapacityRequirement=30, roomTypeRequirement=null, roomProjectorRequirement=false, roomRecorderRequirement=false, roomSMARTBoardRequirement=false], CourseComponent [id=0, type=WPO, term=S2, contactHours=26, startingDate=2, roomCapacityRequirement=30, roomTypeRequirement=null, roomProjectorRequirement=false, roomRecorderRequirement=false, roomSMARTBoardRequirement=false]]

Dit is de sysout van de course die ik net heb gemaakt. Ik had voor beide course components de projector aangevinkt en deze staat hier op false.

**Comment by nicocarraggi** [comment]
De course wordt wel correct toegevoegd in de database ( op die projector na ). Is het eventueel mogelijk om bij het succesvol toevoegen van een course, automatisch terug te gaan naar de lijst van courses? Nu blijf je op de pagina met de course die je net hebt toegevoegd en dat lijkt dat er niets is gebeurd.

**Comment by Timbo925** [comment]
Dus het probleem is als je een nieuw vak aanmaakt en dan  coursecomponents hebt dat de text ernaast niet overeen komt??

Terug gaan naar de vorige pagina is ook mogelijk.

**Comment by Timbo925** [comment]
Bij een nieuw course lijkt me toch alles in orde?

**Comment by nicocarraggi** [comment]
ik bedoel de tekst in de popups.

**Comment by Timbo925** [comment]
Zou moeten werken nu lokaal bij mij gestest. Als je dus toevoegt komt er loading zodat ge weet dat het met iets bezig is. + Je kan ook zonder coursecomponents toevoegen.

Popup text is ook aangepast
