### ISSUE TITLE
Bootstrap issue IE 11

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#25]
Toevallig was ik aan het testen in IE 11 en de login pagina ziet er als volgt uit:

![image](https://f.cloud.github.com/assets/5703745/1769836/78e037ac-677b-11e3-916d-9f39ec198507.png)

Het is duidelijk dat er een probleem is met de schaling. In Chrome werkt alles goed.

**Comment by Timbo925** [comment]
Hopelijk makkelijk op te lossen. Typish IE

**Comment by MPieter** [comment]
Vermits we deze layout niet meer gebruiken, is dit issue niet meet van toepassing.
