### ISSUE TITLE
Sortable Programms Front Page

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#257]
@svdvonde 

De lijst van programmas op de front page is niet gesorteerd. Ik heb al iets geprobeerd maar het sorteren lukt niet. Zou jij er nog eens naar willen kijken want zoeken is zo wel niet handig zeker als we het juiste programma moeten selecteren voor de demo.

**Comment by svdvonde** [comment]
Mee bezig

**Comment by svdvonde** [comment]
Sluit maar
