### ISSUE TITLE
Session ID duplicatie

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#28]
Momenteel is er nog duplicatie van session ID's. Dit wil zeggen dat users meerderre coocies tegelijk kunnen bezitten. Opzicht goed idee als je gebruik maakt voor verschillende computers gebruikt maar zou hier graag een limiet op zetten. Voorstel is limiet van 5.

Dit moet gebeurden bij insertSession(session). Dus gewoon 1 overschrijven als zelfde user als meer als  5 keer aanwezig is in de database.

**Comment by gaethofs** [comment]
Vindk goed voorstel. Pro!

**Comment by MPieter** [comment]
Dit misschien dan ook best opschrijven in SRS:

https://github.com/CalZoneVUB/Documents/issues/52

**Comment by gaethofs** [comment]
Overgestapt naar Spring Security.
