### ISSUE TITLE
Unit Tests voor database

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#38]
Ondanks dat Jens zei dat voor operaties naar de database er geen unit tests moeten geschreven worden, zou ik toch willen dat er voor DbTranslate unit tests geschreven worden.

~~Want voor het moment is die klasse volledig broken.~~

@svdvonde Wie is er verantwoordelijk voor testen te schrijven ?

**Comment by svdvonde** [comment]
In principe moeten alle tests voor een klasse geschreven worden door de programmeur van die klasse, net na hij die klasse heeft afgewerkt (om de werking te bevestigen) De moeilijkheid aan die specifieke klasse testen is dat je (zoals ik aanhaalde) moet testen of bepaalde data wel degelijk correct in de database is opgenomen. Die queries sturen gaat via een DBLink object (als ik me niet vergis), en daarin is de configuratie van de database hardcoded. In principe zou je een dummy-database moeten opzetten (iets lokaal, SQLLite-achtig misschien?) en daarin alle tests runnen.

**Comment by MPieter** [comment]
@svdvonde Das wel niet het antwoord op mijn vraag :(

Dus @nicocarraggi schrijft gij die testen ?

**Comment by MPieter** [comment]
Niet meer van toepassing vermits we nu Hibernate gebruiken.
