### ISSUE TITLE
DbTranslate

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#39]
Doordat ik moest zoeken in DbTranslate naar een fout die voorkomt in selectUserByUsername kwam ik ook volgende code tegen:

```
public DbTranslate() {
    DbLink.openConnection();
}
```

Wat doet dat stuk juist ?  Want alle methodes die erin staan zijn toch static. Dus wordt dat dan wel uitgevoerd ?

**Comment by Timbo925** [comment]
Dit opent de connectie met de database. Ik heb dit in mijn fork al beetje aangepast dat dit anders gaat gebeuren en ook moet werken op windowns enz... Dit gebeurd met spring-beans. Welke fout kom je tegen bij selectUserByUsername? 

Ik zal mijn verbeteringen al pushen. Mijn password deel werkt nog niet volledig maar db connecties moeten wel al goed zijn.

**Comment by MPieter** [comment]
De volgende fout verschijnt:

java.lang.NullPointerException
    com.vub.db.DbLink.executeSqlQuery(DbLink.java:28)
    com.vub.db.DbTranslate.selectUserByUsername(DbTranslate.java:289)
    com.vub.controller.ProfilePageControler.viewProfil(ProfilePageControler.java:22)

met volgende controller:

@Controller
public class ProfilePageControler {

```
@RequestMapping(value= "/profile", method = RequestMethod.GET)
public String viewProfil(ModelMap model, Principal principal) {

    String username = principal.getName();
    User user = DbTranslate.selectUserByUsername(username);
    model.addAttribute("user", user);
    return "profile";
}
```

}

Dus dat doet mij dan toch vermoeden dat er in "com.vub.db.DbTranslate.selectUserByUsername" iets fout gaat.

**Comment by nicocarraggi** [comment]
Wat meteen opvalt is dat hier geen gebruik is gemaakt UserDao ? Normaal gezien mag DbTranslate niet worden gebruikt in de code ! 

Eerst een "userDao" aanmaken en dan "findByUserName(String username)" gebruiken.

String username = "test";
UserDao userDao = new UserDao();
userDao.findByUserName(username);

Volgens mij is er niets fout aan selectUserByUsername.

**Comment by Timbo925** [comment]
Ge moet gebruik maken van een UserDao (User Database Object) om een User op te vragen. Dus iets van deze form. Dit is expres so gedaan zodat elke object zijn eigen laag van abstractie heeft voor opgeslagen te worden in de db. Hieronder een voorbeeld hoe het zou moeten. 

   User user = new User();
   UserDao userDao = new UserDao();
   user = userDao.findByUserName(userName);

**Comment by Timbo925** [comment]
Wayoo Dubble teamed :P

**Comment by nicocarraggi** [comment]
Haha zalig !

En weet ook dat, indien de username niet bestaat in de database er "return null;" gebeurt. Dus misschien test je met een foute username?

Je moet altijd checken of het null is.

Vb. ( uit ActivateAccountController.java )

```
                    UserDao userDao = new UserDao();
        User user = new User();
        user = userDao.findByUserName(activationKey.getUserName());
        System.out.println("Found user by actiavtion key: " + user);
        if (user == null) {
            System.out.println("no user found with username in system for activation key");
            return "ActivatedNotAccount";
        } else {
            userDao.upgradeNotEnabledUser(user);
            activationKeyDao.deleteActivationKey(activationKey);
            return "ActivatedAccount";
        }
```

**Comment by MPieter** [comment]
Thanks guys ! 

Het was inderdaad mijn fout, ik was even vergeten dat we een extra abstractielaag toegevoegd hadden met die extre Database objects.

& Is die check voor null ook nodig wanneer het inloggen al succesvol gebeurd is ?
