### ISSUE TITLE
Database: UpdateUser

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#41]
Momenteel wordt er in de methode "updateUser" enkel passwoord en taal ge-update.

Zou je dit kunnen aanpassen dat dit alle velden update? Vermits ik veronderstel dat ik deze methode moet gebruiken wanneer de user zijn profielgegevens heeft aangepast, dit betekent dus ook voornaam, achternaam, etc...

Stuk code in kwestie: (DbTranslate.java , lijn 136 - 145)

```
// UPDATE

// updateUser will only update Password and Language.

public static void updateUser(User user) {
    DbLink.executeSql("UPDATE Users" + " SET Password = '"
            + user.getPassword() + "', Language = '" + user.getLanguage()
            + "'" + " WHERE Username = '" + user.getUserName() + "';");
}
```

Akkoord ?

**Comment by Timbo925** [comment]
Is dit opgelost?

**Comment by nicocarraggi** [comment]
Nu worden volgende attributen geupdate:
- Password
- Language
- UserTypeID
- LastName
- FirstName
- Email
- BirthDate

Dus enkel Enabled wordt niet aangepast, wat logisch is want dat mag alleen via upgradeNotEnabledUser(User).
