### ISSUE TITLE
Database: UserTypes

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#43]
Zoals besproken op 28/02, hebben we volgende users in ons systeem:
1. student
2. assistant
3. professor
4. admin

Gelieve dit aan te passen in tabel UserTypes.

**Comment by Timbo925** [comment]
Vergeet dan ook niet het de functie aan te passen die een user van niet-actief naar actief promoveert. Momenteel zet deze ook user naar type 2 en da moet dus type 1 blijven (de defaut)

**Comment by nicocarraggi** [comment]
Moet usertype met ID 0 dan nog altijd IS_AUTHENTICATED_ANONYMOUSLY zijn? Of moet dat nu vervangen worden door ROLE_STUDENT ?

**Comment by MPieter** [comment]
Role_User is best denk ik !

**Comment by MPieter** [comment]
@nicocarraggi Is dit nu al geimplementeerd ?

**Comment by nicocarraggi** [comment]
Ja hoor :)
