### ISSUE TITLE
Database: Maak RoomDao

### ISSUE THREAD

**Issue by svdvonde** [CalZoneVUB/CalZone#45]
Er is een object nodig om rooms op te slaan in de database, om ze weer te geven op een webpagina (en toe te voegen, enz)

**Comment by Timbo925** [comment]
Assigned aan Niko. Niko ge moet dus gewoon een ArrayList<Rooms> terug geven uit de database. 

Voor sam ik denk dat via de DB kant het nodig is JSON to ontvangen? (zo doet christophe het toch denk ik) Ik zal dus een ArrayList<Rooms> naar JSON maken.

**Comment by Timbo925** [comment]
Zo kunde het verwachten moest het via json verlopen. Het toevoegen van info mag dan ook via json formaat verlopen moest dit zo gaan 

``` json
[{"name":"Class room","places":80,"building":"B","floor":"0","number":31,"hasProjector":false,"hasRecorder":false,"hasSmartBoard":false},{"name":"Class room","places":172,"building":"D","floor":"0","number":2,"hasProjector":false,"hasRecorder":false,"hasSmartBoard":false},{"name":"Class room","places":200,"building":"D","floor":"0","number":3,"hasProjector":false,"hasRecorder":false,"hasSmartBoard":false},{"name":"Class room","places":127,"building":"D","floor":"0","number":5,"hasProjector":false,"hasRecorder":false,"hasSmartBoard":false},{"name":"Class room","places":140,"building":"D","floor":"0","number":7,"hasProjector":false,"hasRecorder":false,"hasSmartBoard":false},{"name":"Class room","places":128,"building":"D","floor":"0","number":8,"hasProjector":false,"hasRecorder":false,"hasSmartBoard":false},{"name":"Class room","places":22,"building":"D","floor":"1","number":5,"hasProjector":false,"hasRecorder":false,"hasSmartBoard":false}]
```

**Comment by gaethofs** [comment]
Dit kan zowel vanuit Spring zelf worden afgehandeld door de controller als volledig via front-end javascript en dan is er wel JSON nodig.

**Comment by Timbo925** [comment]
Kstel voor dat degene die het moeten schrijven mogen beslissen hoe ze het willen implementeren. Langs de controller kant is het makkelijk om json te serven van bepaalde objecten moest dit nodig zijn.
