### ISSUE TITLE
Email-model

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#48]
Door die merge van @svdvonde zit ik nu met 2 email modellen in mijn code. 
- Email
- EmailMe

Welke gaan we houden ?

**Comment by gaethofs** [comment]
Wat ik heb verstaan uit alle code die er passeert zit er een verschil tussen de twee klassen. En de klasse EmailEmail is ook ergens ter sprake gekomen dacht ik.

**Comment by svdvonde** [comment]
Ik heb die Email gemaakt omdat redenen. Vraag ernaar op vergadering :)

**Comment by MPieter** [comment]
Das dus niet aan bod gekomen op de vergadering als ik mij niet vergis... 

Dus @svdvonde wat is nu de reden hiervoor ?

**Comment by Timbo925** [comment]
Naar mijn weten kwam dit doordat sam zijn eigen validator had geschreven. Dus 1 van de 2 moet nog verwijderd worden. EmailMe word volgens mij wel gebruikt voor mails te verzenden en gerefereerd in xml files. Dit moet dus nog eens goed bekeken worden.

**Comment by svdvonde** [comment]
EmailMe gebruikt validator in het object, ik vond het mooier en praktischer om validator als aparte klasse te gebruiken. Dus, omdat die emailme misschien al ergens anders gebruikt werd heb ik een nieuwe email klasse gemaakt zonder constraints op de waarden. Ik ben nog steeds van mening dat het mooier, praktischer en uitbreidbaarder is om constraints op waarden in een externe klasse te bepalen ipv in de klasse zelf.

**Comment by MPieter** [comment]
Ik stel dus volgende fix voor:

We gebruiken vanaf validators als aparte klassen, zodanig dat we met annotaties kunnen werken voor validatie in het model kunnen werken.

Anders moet ge in u controller nog extra java code toevoegen voor validatie, en dat vind ik ook minder mooi.

De klasse Email moet dus verwijderd worden.

**Comment by Timbo925** [comment]
Ik zal het ook nog eens bekijken wat de voor/nadelen zijn voor ik een beslissing maak. We houden deze aanpassing tot na de presentatie.

**Comment by MPieter** [comment]
Gefixed: we behouden het Email model waarbij we gebruik maken van validators als annotatie.
