### ISSUE TITLE
RoomEquipment

### ISSUE THREAD

**Issue by nicocarraggi** [CalZoneVUB/CalZone#59]
Momenteel geven alle rooms uit de CSV file FALSE op alle Equipments. @Timbo925

**Comment by Timbo925** [comment]
Is dit al gefixed of niet?

**Comment by MPieter** [comment]
@nicocarraggi Reactie ?

**Comment by nicocarraggi** [comment]
Neen nog niet gefixed met dat dat gebeurde bij het inlezen van de csv en we dit hadden "uitgezet" omdat ze al geimporteerd waren! Zal er morgen naar kijken :)

**Comment by nicocarraggi** [comment]
Werkt nu zoals het moet !
