### ISSUE TITLE
Bootstrap Tables

### ISSUE THREAD

**Issue by nicocarraggi** [CalZoneVUB/CalZone#62]
Misschien is het een goed idee van sortable tables te gebruiken?

Momenteel heb ik voor EnrolledCourses het volgende gebruikt:
    Collections.sort(courseArrayList);

Dus nu worden de courses geprint in alfabetische volgorde. (vroeger op courseID)

@gaethofs @fsuarezg @svdvonde @MPieter

**Comment by MPieter** [comment]
Dat lijkt mij een goede oplossing.

De bedoeling is dat er nog zoekfilters opkomen zodanig dat ge gemakkelijk bepaalde vakken kunt selecteren.

**Comment by MPieter** [comment]
Volgende moet nog geïmplementeerd worden:
- Aan de client-side moet er sortering ingebouwd worden via JavaScript. Door op de kolomnamen te klikken moet de sortering aangepast kunnen worden.
- Zoekfilters implementeren.

**Comment by nicocarraggi** [comment]
http://stackoverflow.com/questions/14713622/twitter-bootstrap-row-filter-search-box

**Comment by svdvonde** [comment]
Issue is opgelost d.m.v. datatables en mag gesloten worden.
https://datatables.net
