### ISSUE TITLE
Confirmatie Mail Account Aanmaken Komt Niet Aan

### ISSUE THREAD

**Issue by fsuarezg** [CalZoneVUB/CalZone#63]
ik probeerde om zelf een account aan te maken voor calzone, maar ik krijg maar geen confirmatie mail gestuurd naar mijn mail.

**Comment by Timbo925** [comment]
Hier is u confirmatie mail link  http://wilma.vub.ac.be:8181/calzone/activate/dp38vbdp29g6ooebt3ucv6icak

Gmail server heef top een of andere manier niet verzonden. Ik bekijk het probleem eens.

**Comment by gaethofs** [comment]
Gmail server? Of wilma? :D

**Comment by Timbo925** [comment]
Gmail blijkbaar want staat wel in verzonden berichten maar krijg een delivery error... :p

**Comment by Timbo925** [comment]
Momenteel opgelost en zou moeten werken.
