### ISSUE TITLE
Issue Test

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#64]
Zou iedereen hieronder eens willen reageren VIA GITHUB aub. Ik wil graag eens zien wie nu effectief github issues leest of niet? Want facebook is geen goede manier van communicatie voor lange, goede, makkelijk ge lezen conversaties.

Thanks

**Comment by endymion64** [comment]
Gelezen :)

**Comment by MPieter** [comment]
Check !

**Comment by fsuarezg** [comment]
gelezen :)

**Comment by svdvonde** [comment]
Met tegenzin gelezen. Spam noem ik het!

**Comment by gaethofs** [comment]
Check!

**Comment by nicocarraggi** [comment]
Final Check !!
