### ISSUE TITLE
RemoveCourse

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#67]
Soort van api nodig voor bepaalde acties te ondernemen in de front end. Dit moet alles vergemakkelijken scheiding ten boven gaan.

Voorbeeld hiervan voor EnrolledCourses

Url:   /calzone/EnrolledCourses/remove/{classId}
Return: {"Status": "Fail" of "Sucess"}

**Comment by MPieter** [comment]
Dit is nu geïmplementeerd. 

De return is wel anders, voor bijvoorbeeld EnrolledCourses is dit: 
    return "redirect:/EnrolledCourses";

Zodanig dat ge terug geleidt wordt naar de overzichtspagina, met een refresh, waardoor de enrollment-list upgedate wordt.
