### ISSUE TITLE
EnrolledCourses werkt niet in laatste commit

### ISSUE THREAD

**Issue by svdvonde** [CalZoneVUB/CalZone#72]
Dus, EnrolledCourses pagina gooit een error als je er naartoe surft

**Comment by MPieter** [comment]
Ik en @nicocarraggi zijn hier momenteel aan het werken. Oplossing komt snel !

**Comment by svdvonde** [comment]
Sowieso liever geen niet-werkende code naar de master branch pushen. Men verwacht dat de master branch op de hoofdrepo altijd werkende spullen bevat :)

**Comment by Timbo925** [comment]
Akkoord met @svdvonde bug word zo snel mogelijk opgelost blijkbaar.

**Comment by MPieter** [comment]
De pagina kan nu terug bezocht worden. Het verwijderen en toevoegen van vakken zijn we wel nog mee bezig.
