### ISSUE TITLE
Time Tracking

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#78]
@gaethofs Time tracking vanavond doorsturen rond 22u dat ik deze kan gebruiken op de slides voor de presentatie. 

Iedereen zet dan voor 22u zijn timetracking erop zodat deze erbij geteld worden.

**Comment by gaethofs** [comment]
Wat het je juist nodig van de timetracking?

**Comment by MPieter** [comment]
Ik denk dat ze voor hetzelfde willen gaan als dat er gezegd is geweest tijdens de presentatie op vorige iteratie:
- Totaal aantal uren gewerkt tijdens 2e iteratie.
- Hoeveelheid uren per activiteit tijdens de 2e iteratie. -> Hier kunnen ze dan een pie chart van maken.

**Comment by gaethofs** [comment]
Gaat momenteel niet. Er is geen onderscheid tussen de 1ste en 2de iteratie. Wel kan er op datum gefilterd worden. Dus dat ik enkel de gegevens gebruik na de deadline van de 1ste iteratie, wat denk ik eigenlijk op hetzelfde uitkomt dan.

Ik zet het op mail.
