### ISSUE TITLE
Nullpointerexception in /EnrolledCourses

### ISSUE THREAD

**Issue by svdvonde** [CalZoneVUB/CalZone#82]
SEVERE: Servlet.service() for servlet [calzoneServlet] in context with path [/calzone] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException

**Comment by nicocarraggi** [comment]
meer uitleg aub?

**Comment by svdvonde** [comment]
Ahja gewoon, ik run het project, ik ga naar "/calzone/EnrolledCourses" en krijg daarna een nullpointerexception

Wat ik er nog wel bij had moeten kopiëren is dit:
<heel dien bazaar>
at com.vub.controller.EnrolledCoursesController.enrolledCoursesPage(EnrolledCoursesController.java:29)

**Comment by nicocarraggi** [comment]
Om naar /EnrolledCourses te gaan moet je nu ingelogd zijn!

**Comment by nicocarraggi** [comment]
/EnrolledCourses is momenteel effectief de lijst van courses die een user volgt.
Je kan wel nog altijd naar /EnrollCourses ( zonder ingelogd te zijn, wat natuurlijk nog moet veranderd worden... zie andere issue), hier krijg je dan de lijst van alle beschikbare vakken.

Maar wacht aub nog even met dat te testen. We zijn momenteel bezig met het toevoegen en verwijderen van vakken voor een user.

**Comment by MPieter** [comment]
Fout zal nu niet meer verschijnen. Indien je de pagina /EnrolledCourses probeert te accessen zonder ingelogd te zijn, wordt je terug geleidt naar de inlogpagina (dus de homepagina).
