### ISSUE TITLE
RoomDao

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#84]
In het room dao moet nog een update komen van een bestaande room (dit is nodig als we een room info willen edditen). Je kan dit doen door een update te schrijven of gewoon  iets van volgende form te gebruiken: http://stackoverflow.com/questions/548541/insert-ignore-vs-insert-on-duplicate-key-update

INSERT...ON DUPLICATE KEY UPDATE zou mss wel moeten lukken denk ik dan.

**Comment by MPieter** [comment]
Is dit issue nog relevant ?

**Comment by Timbo925** [comment]
Nee
