### ISSUE TITLE
Classrooms

### ISSUE THREAD

**Issue by Timbo925** [CalZoneVUB/CalZone#87]
Geen optie om classrooms te deleten voor de admin op pagina /classroom.

**Comment by MPieter** [comment]
Zijn er al admins in ons systeem ?

**Comment by Timbo925** [comment]
Momenteel niet echt nee maar deze pagina zal enkel berijkbaar worden door een admin. Maar de pagina zelf moet wel helemaal werken

**Comment by nicocarraggi** [comment]
Done ?!

**Comment by MPieter** [comment]
Nee Sam is daar nog aan bezig denk ik.

**Comment by Timbo925** [comment]
Bestaat nog niet echt denk ik. Sam was ook nog bezig met het toevoegen van courses dus als dit af kan hij het verwijderen ook al doen. Bestaat al voor trajecten enzo dus geen probleem normaal gezien
