### ISSUE TITLE
Url: Calzone today

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#93]
Bij het gebruiken van de domain naam calzone.today werken sommige redirects niet meer.

**Comment by MPieter** [comment]
Ik zie dat ze dat ze deze url calzone/today willen gebruiken in de presentatie. 

Dan moet hier toch eens naar gekeken worden: @Timbo925. Meer uitleg van wat jij hier al van gefixt hebt?

**Comment by Timbo925** [comment]
Gebruik voorlopig gewoon de wilma link mannen. Die redirect word door nils gedaan van zijn server en deze is momenteel niet online. Ben niet zeker dat dit dus op tijd kan worden opgelost
