### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by endymion64** [CalZoneVUB/CalZone#94]
# Hoe zit het logging systeem in elkaar?
## Conclusie uit sectie 1.3.2 van de [Spring documentatie](http://docs.spring.io/spring/docs/3.1.0.M1/spring-framework-reference/html/overview.html#d0e748)

Spring ondersteunt vele frameworks voor logging. Standaard gebruikt Spring JCL (Jakarta Commons Logging API), maar zelf zegt de documentatie van Spring dat dit misschien geen geweldig iets is om zelf te gebruiken doorheen u code. Zij zeggen dat het beter/makkelijker is om SLF4J (Simple Logging Facade for Java) te gebruiken. Dit is een abstractielaag zodat er verscheidene soorten logging frameworks kunnen gebruikt en verwisseld worden 'at deployment' zonder daarvoor heel de source code te moeten wijzigen (slechts kleine aanpassingen in pom.xml zullen er nodig zijn naast een configuratie van u backbone framework). 

Ik heb dus reeds de nodige dependencies ingeladen om dit te initialiseren en ben nu de [manual van SLF4J](http://www.slf4j.org/manual.html) aan het lezen en aan het spelen met logging op mijn eigen branch.

Voorlopig is de backbone voor logging [log4j versie 1.2](https://logging.apache.org/log4j/1.2/). De configuratie van deze backbone gebeurt in de file ~~'log4j.properties'~~ 'log4j.xml'. Deze is terug te vinden in de main/resources folder (bij messages.properties enzo). Deze [tutorial](http://www.tutorialspoint.com/log4j/index.htm) kan je raadplegen voor een simpele uitleg van de werking van log4j. Google'en naar vele voorbeeldjes om te zien hoe de XML-boom wordt opgesteld.
## GEBRUIK van SLF4J

In een klasse waar je gegevens wil loggen roep je een instantie van een SLF4J Logger Object op. Vervolgens stuur je alle berichten die je wil loggen naar dit object. **BELANGRIJK:** Er zijn 4 soorten logberichten. Hieronder een voorbeeldklasse:

``` java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LoggingExample {
    final Logger logger = LoggerFactory.getLogger(getClass());
    public void f(){
        logger.info("Hello World");
        logger.info("This is a logging test");
        logger.debug("This is a debug message with a parameter at the end: {}", 5);
        logger.error("This is an error message with parameter at the end: {}", 6);
        logger.warn("This is a warning message with parameter at the end: {}", 6);
    }
}
```

Voor meer info verwijs ik naar de [JavaDoc](http://www.slf4j.org/api/org/slf4j/Logger.html) van het object. Hier heeft is de gehele [API](http://www.slf4j.org/api/overview-summary.html) van SLF4J.
## Huidige configuratie log4j

Je configureert ~~'log4j.properties'~~ 'log4j.xml' naargelang hoe je stuff gelogd wil (in een specifieke file of specifieke UNIX console...) en vervolgens hoef je je weinig aan te trekken over waar welke log te staan komt. Doorlees de [tutorial](http://www.tutorialspoint.com/log4j/index.htm) indien je hiermee wil knoeien en Google naar de XML.

Voorlopig heb ik dit plan in ogen en quasi 90% geïmplementeerd:
- 3 locaties waar logs terecht kunnen komen: 1 voor debug, 1 UNIX console (system.out) en 1 voor gewone log (alles buiten debug)
- Opzet debug log: de debug logs worden in een aparte folder gestoken. Bovendien zal er per dag een nieuwe log in deze folder starten kwestie van orde op zaken te houden. (gebeurt automatisch)
- Opzet gewone log file: alles behalve debug berichten
- Opzet console log: alle logs passeren op de console?

**Comment by Timbo925** [comment]
Ik heb dit document toegevoegd als een readme in het home directory. Zeker goed genoege uitleg om bij te houden. Als je dus een voorbeeldje hebt gemaakt dat werkt in de code voeg het daar dan ook toe. Hebben we een goede guide voor iedereen.

**Comment by MPieter** [comment]
Prima! Heeft @yocoppen hier nog iets aan te voegen ? Anders kunnen we dit issue sluiten.

**Comment by endymion64** [comment]
neen, als dit in de readme staat, zal ik dit sluiten.

**Comment by MPieter** [comment]
@yocoppen Als ik het dus goed begrijp, gebruiken we log4j als logging framework die gebruik maakt van de SLF4J API.

Mijn vraag: heb je ook overwogen om Logback te gebruiken i.p.v. log4j ? Ik ben dit toevallig tegengekomen toen ik bezig was aan de schedular. Ik lees namelijk dat Logback eigenlijk de opvolger is van log4j, waardoor log4j dus deprecated is. 

http://logback.qos.ch/
http://logback.qos.ch/reasonsToSwitch.html

**Comment by endymion64** [comment]
Ik had het gelezen in de documentatie van SLF4J dat logback de preferentie is, maar daar had ik geen extra info over qua configuratie dus had ik voor log4j gekozen. Ook omdat dit framework het meest gekend was als ik google'de, maar ik kan er logback insteken als backbone, maar dan ga ik eerst weer moeten onderzoeke hoe je daar de configuratie doet

**Comment by gaethofs** [comment]
Bijna depricated of niet. Als het goed werkt stem ik voor dat we momenteel dit gebruiken en hier niet te veel tijd met verliezen? Dit is al een mooie en duidelijke doc.

**Comment by MPieter** [comment]
Oke laat dan maar zo. Het werkt, das al het voornaamste.
