### ISSUE TITLE
Deployment to Wilma

### ISSUE THREAD

**Issue by MPieter** [CalZoneVUB/CalZone#97]
Youri, ik heb een vraag voor u. Ik ben bezig aan het script te schrijven voor te deployen naar wilma. Hiervoor moet ik met ssh een verbinding leggen en een paar commandos uitvoeren. Om onmiddellijk de commando's uit te voeren gebruik ik volgende code:

> ssh se2_1314@wilma.vub.ac.be "cd apache-tomcat-7.0.47/bin; ./shutdown.sh; ./startup.sh"

En hier zit juist het probleem. Want dat doet niet wat het moet doen, de commandos worden wel degelijk uitgevoerd, maar blijkbaar in een andere "modus", waardoor de website niet werkt. Maar als ik het zo doe:

> ssh se2_1314@wilma.vub.ac.be
> 
> > cd apache-tomcat-7.0.47/bin
> > ./shutdown.sh
> > ./startup.sh

Dan werkt de website op de server wel. Maar helaas kan ik deze aanpak niet gebruiken, want dit moet manueel gebeuren.

Weet gij hier soms meer over ?

**Comment by Timbo925** [comment]
In command line gebruikte && om dinges na elkaar te doen. En waarschijnlijk ook -p pasword moeten doen voor de ssh verbinding

**Comment by MPieter** [comment]
De '&&' heeft het gedaan, bedankt ! Voor het password heb ik wel gebruik gemaakt van 'sshpass' vermits er geen optie is bij ssh om het password mee te geven.

Het script werkt nu volledig !

**Comment by endymion64** [comment]
Ik lees het nu maar pas. Ik was de hele dag weg. Gelukkig is het al opgelost
